# Site settings
title: 生命不止，折腾不息
author: dongliang
author_avatar: /images/header.jpg
email: dongliang5250@outlook.com
description: 生命不止，折腾不息 
url: "https://adongliang.github.io"
# domain: "http://dongyado.com"
# github_username: dongyado
# github_site_repo: dongyado/dongyado.github.io
disqus: monsterslayer
google_analytics: UA-117417336-1


# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
    syntax_highlighter: rouge
    extensions: ["fenced_code_blocks", "autolink", "tables", "smart"]

sass:
    style: :compressed
    sass_dir: _sass

permalink: pretty
excerpt_separator: "<!-- more -->"

# path
categories_path: categories/
tags_path: tags/


gems:
  - jekyll-sitemap
